spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
#    druid
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
#  redis:
#    host: 192.168.110.110
#    port: 6369
#    password: 147369258
#    pool:
#      max-idle: 10
#      max-wait: 3
#      max-active: 10
#    tomcat:
#      validation-query:
# mybatis
mybatis:
  type-aliases-package: com.xiyifne.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/xiyifen/miaosha/dao/*.xml
# redis
redis:
  host: 192.168.110.110
  port: 6379
  password: 147369258
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3



